name: Get pods, svc, endpoints
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/kubectl@master
        name: get pods
        env:
          KUBE_CONFIG: ${{ secrets.PILOT_KUBE_CONFIG }}
        with:
          args: get pods
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.PILOT_KUBE_CONFIG }}
        with:
          args: get svc  
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.PILOT_KUBE_CONFIG }}
        with:
          args: get endpoints    

      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
      - name: Output Run SHA
        run: echo ${{ github.sha }}